### ISSUE TITLE
Please maintain this project!

### ISSUE THREAD

**Issue by josephfinlayson** [uerceg/play-install-referrer-react-native#14]

**Comment by uerceg** [comment]
Hi @josephfinlayson,

It's been a while since I checked it last time, but in theory I didn't plan to abandon it. Did you have anything specific in mind which you would like to see being done when opening this issue?

Cheers

**Comment by josephfinlayson** [comment]
@uerceg actually not really, It's now in my app with 30,000 monthly users, so I am just relying on this package to be kept up to date. It would be good to add `npm audit` to your CI pipeline, to make sure you're not bundling possibly insecure dependencies

**Comment by uerceg** [comment]
Gotcha, thanks for the advice, will be done. I will try to find some time to update native install referrer library to latest version which Google has shipped and will `npm audit` as part of that update.
