### ISSUE TITLE
 Install referrer = utm_source=(not%20set)&utm_medium=(not%20set)

### ISSUE THREAD

**Issue by Shahnewaj** [uerceg/play-install-referrer-react-native#16]
Hi , 
referrer details is not available. 
Always give this :  utm_source=(not%20set)&utm_medium=(not%20set)
Where as url has referral code  like :
https://play.google.com/store/apps/details?id=com.arogga.app&referrer=utm_source%3Darogga%26utm_medium%3Dlink%26utm_term%3Drefer%26utm_content%3D123456%26utm_campaign%3Dtest
or :  https://play.google.com/store/apps/details?id=com.arogga.app&referrer=1234567

nothing is working . 
I need actually the second url type to be working 

<img width="1088" alt="Screenshot 2021-09-29 at 12 31 45 AM" src="https://user-images.githubusercontent.com/6037819/135145551-00d6400f-b29e-4a49-80f5-8e0cc353dfbd.png">

**Comment by uerceg** [comment]
Hi @Shahnewaj, hi @danruss,

How are you guys performing this test where you're getting organic value back?

**Comment by uerceg** [comment]
As far as I know, in order to run actual test to see if install referrer value is properly captured, you would need to actually redirect to your app in Play Store, download it and then check what is the value of the referrer. Back in the days when install referrer value has been delivered with the INSTALL_REFERRER intent, one could simply ping the app with `adb` command to broadcast this intent. But nowadays with install referrer library (which is bonded to Play Store app service under the hood), I am not sure if one can test this easily without having an app in the Play Store. For any local test you might do, I think that organic referrer value will always be returned by default.

**Comment by vignesh-pibase** [comment]
26

You can test it without uploading on Playstore.

I did in following way.

    I have created urls like https://play.google.com/store/apps/details?id=fullpackagename&referrer=utm_source%3Dmysource&utm_content%3Dmycontent&hl=en
    I have fired this url from my mail. It redirects to Playstore
    From command Prompt(using adb command) , I have installed desired apk.
    On Playstore, "install" button will be replaced with "open" button and I clicked on that. it is working

**Comment by uerceg** [comment]
Exactly @vignesh-pibase,

Thank you for this answer. I will add the guide based on it to the README section of the repo as well. 👍 

In theory, you don't need to run extra miles to wait to see `Install` turning in to `Open` after you have installed the app on your device. I believe that just a bit prettified version of your guide should look like this:

- In case you want to run the test with package name of your app, you need to make sure to have that app released on the Play Store.
- In case you don't have any app in the Play Store, for this test you can try to "hijack" package name of any app that's published on the app store.
- Make sure not to have app with with that package name installed on your test device / emulator.
- Place the test URL (for example: https://play.google.com/store/apps/details?id=fullpackagename&referrer=utm_source%3Dmysource&utm_content%3Dmycontent&hl=en) somewhere where you'll be able to click on it from the test device / emulator. If out of ideas where or how, https://neocities.org/ can be a place to quickly launch a web page where you can place this URL.
```xml
<p><a href="https://play.google.com/store/apps/details?id=fullpackagename&referrer=utm_source%3Dmysource&utm_content%3Dmycontent&hl=en">Install referrer test URL</a></p>
```
- Open this web page from your test device / emulator and click on `Install referrer test URL`.
- Once redirected to the Play Store page of the app, don't install it.
- Install your app locally (via `adb`, Android Studio, `react-native` CLI, whatever you use) on your test device / emulator.
- Invoke plugin's API and you should receive install referrer data from the URL you've clicked.

Closing this ticket now, but in case anyone has any follow up questions, feel free to comment / reopen.

Cheers.
