### ISSUE TITLE
Cannot read property 'getInstallReferrerInfo' of undefined

### ISSUE THREAD

**Issue by Rushabhgedam** [uerceg/play-install-referrer-react-native#3]
**Describe the bug**
Imported the package, when I log it like
console.log(PlayInstallReferrer)
I get the data as
![image](https://user-images.githubusercontent.com/37809971/105449157-c9313c00-5c9d-11eb-860d-4a8e78a24ebc.png)
but when I add the data function call it appears as undefined.

**Environment**
Please describe your working environment:
- Windows,
- React native version 0.59.5

**Screenshots**
![image](https://user-images.githubusercontent.com/37809971/105448992-69d32c00-5c9d-11eb-87fe-2bb4a8943850.png)

**Comment by uerceg** [comment]
Hi @Rushabhgedam 

Can you share the integration code from your app where you're importing and using plugin's API?

Cheers

**Comment by uerceg** [comment]
Hi @Rushabhgedam 

Any update on this one?

Cheers

**Comment by uerceg** [comment]
Closing this one due to inactivity. In case you get back to this issue, feel free to comment / reopen.
